services:
  ig-archiver:
    build:
      context: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      DATA_DIR: /data
    volumes:
      - ./server/data:/data
    restart: unless-stopped
